# Generated by Django 5.2.14 on 2026-05-14 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failure', 'Échec connexion'), ('logout', 'Déconnexion'), ('user_create', 'Création utilisateur'), ('user_update', 'Mise à jour utilisateur'), ('expert_verify', 'Vérification expert'), ('payment', 'Paiement'), ('subscription', 'Abonnement'), ('request', 'Demande de service'), ('review_moderation', 'Modération avis'), ('file_upload', 'Téléversement fichier'), ('admin_action', 'Action administrateur')], db_index=True, max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=128)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx')],
            },
        ),
    ]
