# Generated by Django 5.2.14 on 2026-05-14 15:47

import django.db.models.deletion
import experts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'spécialité',
                'verbose_name_plural': 'spécialités',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible')], db_index=True, default='unavailable', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=experts.models.expert_avatar_upload)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
                ('specialties', models.ManyToManyField(blank=True, related_name='experts', to='experts.specialty')),
            ],
            options={
                'verbose_name': 'profil expert',
                'verbose_name_plural': 'profils experts',
            },
        ),
        migrations.CreateModel(
            name='ExpertDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identity', "Pièce d'identité"), ('certification', 'Certification'), ('professional', 'Justificatif professionnel'), ('cv', 'CV'), ('other', 'Autre')], max_length=32)),
                ('file', models.FileField(upload_to=experts.models.expert_document_upload)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expert_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='experts.expertprofile')),
            ],
            options={
                'verbose_name': 'document expert',
                'verbose_name_plural': 'documents experts',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='expertprofile',
            index=models.Index(fields=['country', 'city', 'availability'], name='experts_exp_country_bda2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='expertprofile',
            index=models.Index(fields=['verification_status', 'availability'], name='experts_exp_verific_53ff26_idx'),
        ),
    ]
