# Generated by Django 5.2.14 on 2026-05-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupé'), ('unavailable', 'Indisponible')], db_index=True, default='unavailable', max_length=20),
        ),
    ]
