# Generated by Django 5.2.14 on 2026-05-14 15:47

import django.db.models.deletion
import requests_system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('accounting_needs', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('in_progress', 'En cours'), ('closed', 'Clôturée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='businesses.businessprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de service',
                'verbose_name_plural': 'demandes de service',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=requests_system.models.request_attachment_upload)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_system.servicerequest')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invité'), ('accepted', 'Accepté'), ('declined', 'Refusé')], db_index=True, default='invited', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.expertprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_links', to='requests_system.servicerequest')),
            ],
            options={
                'verbose_name': 'affectation expert',
                'verbose_name_plural': 'affectations experts',
                'unique_together': {('service_request', 'expert')},
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='experts',
            field=models.ManyToManyField(blank=True, related_name='service_requests', through='requests_system.ServiceRequestExpert', to='experts.expertprofile'),
        ),
    ]
