# Generated by Django 5.2.14 on 2026-05-14 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', "Dans l'application"), ('email', 'E-mail'), ('sms', 'SMS')], default='in_app', max_length=16)),
                ('event_type', models.CharField(choices=[('request_received', 'Demande reçue'), ('request_accepted', 'Demande acceptée'), ('subscription_expiring', 'Abonnement bientôt expiré'), ('payment_confirmed', 'Paiement confirmé'), ('generic', 'Générique')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
